Add Windows support to download-df, install wget, strawberryperl

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -1,6 +1,6 @@
 name: Build
 
-# on: [push, pull_request]
+on: [push, pull_request]
 
 jobs:
   build:
@@ -83,53 +83,53 @@ jobs:
       run: |
         rm -rf "$DF_FOLDER"
 
-  lint:
-    runs-on: ubuntu-18.04
-    steps:
-    - name: Set up Python 3
-      uses: actions/setup-python@v2
-      with:
-        python-version: 3
-    - name: Set up Ruby 2.7
-      uses: actions/setup-ruby@v1
-      with:
-        ruby-version: 2.7
-    - name: Install Lua
-      run: |
-        sudo apt-get update
-        sudo apt-get install lua5.3
-    - name: Clone DFHack
-      uses: actions/checkout@v1
-      with:
-        submodules: true
-        # don't need tags here
-    - name: Check whitespace
-      run: |
-        python travis/lint.py
-    - name: Check Authors.rst
-      if: success() || failure()
-      run: |
-        python travis/authors-rst.py
-    - name: Check for missing documentation
-      if: success() || failure()
-      run: |
-        python travis/script-docs.py
-    - name: Check Lua syntax
-      if: success() || failure()
-      run: |
-        python travis/script-syntax.py --ext=lua --cmd="luac5.3 -p" --github-actions
-    - name: Check Ruby syntax
-      if: success() || failure()
-      run: |
-        python travis/script-syntax.py --ext=rb --cmd="ruby -c" --github-actions
+  # lint:
+  #   runs-on: ubuntu-18.04
+  #   steps:
+  #   - name: Set up Python 3
+  #     uses: actions/setup-python@v2
+  #     with:
+  #       python-version: 3
+  #   - name: Set up Ruby 2.7
+  #     uses: actions/setup-ruby@v1
+  #     with:
+  #       ruby-version: 2.7
+  #   - name: Install Lua
+  #     run: |
+  #       sudo apt-get update
+  #       sudo apt-get install lua5.3
+  #   - name: Clone DFHack
+  #     uses: actions/checkout@v1
+  #     with:
+  #       submodules: true
+  #       # don't need tags here
+  #   - name: Check whitespace
+  #     run: |
+  #       python travis/lint.py
+  #   - name: Check Authors.rst
+  #     if: success() || failure()
+  #     run: |
+  #       python travis/authors-rst.py
+  #   - name: Check for missing documentation
+  #     if: success() || failure()
+  #     run: |
+  #       python travis/script-docs.py
+  #   - name: Check Lua syntax
+  #     if: success() || failure()
+  #     run: |
+  #       python travis/script-syntax.py --ext=lua --cmd="luac5.3 -p" --github-actions
+  #   - name: Check Ruby syntax
+  #     if: success() || failure()
+  #     run: |
+  #       python travis/script-syntax.py --ext=rb --cmd="ruby -c" --github-actions
 
-  check-pr:
-    runs-on: ubuntu-latest
-    if: github.event_name == 'pull_request'
-    steps:
-    - name: Check that PR is based on develop branch
-      env:
-        BASE_BRANCH: ${{ github.base_ref }}
-      run: |
-        echo "PR base branch: $BASE_BRANCH"
-        test "$BASE_BRANCH" = develop
+  # check-pr:
+  #   runs-on: ubuntu-latest
+  #   if: github.event_name == 'pull_request'
+  #   steps:
+  #   - name: Check that PR is based on develop branch
+  #     env:
+  #       BASE_BRANCH: ${{ github.base_ref }}
+  #     run: |
+  #       echo "PR base branch: $BASE_BRANCH"
+  #       test "$BASE_BRANCH" = develop
